### ISSUE TITLE
Investigate if zedboard is functional

### ISSUE THREAD

**Issue by nicklasfrahm** [nicklasfrahm/spro4-em#1]
As we propably all recognized, the zedboard has a delicious smell to it, which might be, because it is fried. Ib proposed to do the **Get started guide**  from _Blackboard_.

**Comment by nicklasfrahm** [comment]
I guess it would make sense to create a folder called `docs` along the way. Then we can populate the folder with a markdown (`.md`) that describes the basics.
@FinnLorenzen Could you look into this?

**Comment by tamaragaede** [comment]
**Hardware user guide** can be found here:
http://zedboard.org/sites/default/files/documentations/ZedBoard_HW_UG_v2_2.pdf

**Comment by nicklasfrahm** [comment]
The **Hardware User Guide** has been integrated into the markdown `INITIAL_SETUP` in PR #2.
